Update to work with recent (1.8) version Parsedown
leblanc-simon/parsedown-checkbox pull request #1
Opened 2018-05-20 03:50 UTC by ms502040

2018-06-08 13:37 UTC, BenjaminHoegh approved these changes

2018-06-08 13:55 UTC, BenjaminHoegh commented
@ms502040 Can you please fix the issue with ul li so its get listed instead of inline

2018-06-08 14:17 UTC, ms502040 commented
@BenjaminHoegh I dont know if you mean this change. If not, can you put screenshot what you mean.

2018-06-08 15:38 UTC, BenjaminHoegh commented
**This is how it should be:**
<img width="233" alt="skaermbillede 2018-06-08 kl 17 32 44" src="https://user-images.githubusercontent.com/22152591/41167222-9a1f138c-6b42-11e8-95ee-bf9e9102484a.png">

**This is what you get:**
<img width="705" alt="skaermbillede 2018-06-08 kl 17 36 49" src="https://user-images.githubusercontent.com/22152591/41167229-9d54a512-6b42-11e8-927b-34bf2da72cfb.png">

2018-06-09 23:29 UTC, ms502040 commented
Ok I updated to produce html code as github. see [README](https://github.com/ms502040/parsedown-checkbox/tree/master/test) in test directory. 
You can update your readme and add github like style:
~~~~css
.task-list-item {
     list-style-type: none;
}
.task-list-item-checkbox {
     margin: 0 0.2em 0.25em -1.6em;
     vertical-align: middle;
}
~~~~

2018-07-11 01:08 UTC, leblanc-simon requested changes
Sorry for the delay, and thanks you very much for your PR!

Could you adapt the tests with your PR, please.

2018-07-11 01:08 UTC, leblanc-simon commented on .gitignore
> +/.idea/
Please, don't add specific editor rules in .gitignore (else, for each PR, we have a new line in .gitignore)

2018-07-11 01:08 UTC, leblanc-simon commented on ParsedownCheckbox.php
> +          $element['handler']['argument'][0] = trim($element['handler']['argument'][0]) . '<br>';
I don't understand this line. If the line finished by 2 or more space, you add a `<br>`. Why ?

2018-07-11 01:08 UTC, leblanc-simon commented on ParsedownCheckbox.php
> +        $element['attributes'] = array('class' => 'task-list-item');
In the master version, we have a CSS class to know if the line is closed or not. With that, we can add CSS rule (like `text-decoration: line-through;`). Could you restore this functionality.

2018-07-11 08:27 UTC, ms502040 commented on ParsedownCheckbox.php
> +        $element['attributes'] = array('class' => 'task-list-item');
this is exactly as in github

2018-07-11 08:29 UTC, ms502040 commented on ParsedownCheckbox.php
> +          $element['handler']['argument'][0] = trim($element['handler']['argument'][0]) . '<br>';
if I want this:
- [ ] aaaa   
next line
- [ ] bbb

after aaaa 2 more space

2019-01-31 01:46 UTC, leblanc-simon commented
The beta version bdf632d7289ac0d67a288d9191a7a4a95c902fac is now compatible with last version (beta) of ParsedownExtra

2019-01-31 01:46 UTC, closed without merging