Format checkbox text
leblanc-simon/parsedown-checkbox pull request #3
Opened 2019-05-29 07:23 UTC by doekenorg

Hi, 

I added `$this->line($text)` to be able to format the labels for the checkboxes. We use the checkboxes to indicate certain tasks are done, and we'd like to be able to link the text to this specific task. 

Also upped the version-number, hope that's ok. I'd love for you to merge this and release a new (beta) tag.

2019-05-29 08:13 UTC, leblanc-simon commented
Hi,

thanks for your PR !

Could you update the unit tests with your use case, please.

2019-05-29 09:47 UTC, doekenorg commented
@leblanc-simon Sure, sorry about that. Slipped my mind. I've "fixed" test 4 as it was not working for me. Used phpunit 7.5 as it is nog in the `composer.json`. 

Thanks!

2019-05-29 23:33 UTC, leblanc-simon requested changes
Thank you very much for the PR. It's a very interesting feature. 

Can you check my comments in the code and tell me if it's OK for you?

2019-05-29 23:33 UTC, leblanc-simon commented on ParsedownCheckbox.php
> +        return '<input type="checkbox" disabled /> ' . $this->line($text);
If you add `$this->line($text)` here, in safe mode or in markup escaped mode, your text will be encoded twice (That's why you had to change the unit test 4).

Could you integrate this code : https://gist.github.com/leblanc-simon/798a4fde9b410b207b32744c728fc706

2019-05-29 23:33 UTC, leblanc-simon commented on ParsedownCheckbox.php
> +        return '<input type="checkbox" checked disabled /> ' . $this->line($text);
If you add `$this->line($text)` here, in safe mode or in markup escaped mode, your text will be encoded twice (That's why you had to change the unit test 4).

Could you integrate this code : https://gist.github.com/leblanc-simon/798a4fde9b410b207b32744c728fc706

2019-05-29 23:33 UTC, leblanc-simon commented on ParsedownCheckbox.php
> +    const VERSION = '0.1.1';
Could you change the version to `0.2.0` because your change introduce a new functionality  :
* **before** : text is not converted
* **after** : text is converted with markdown

I follow https://semver.org/

2019-05-29 23:33 UTC, leblanc-simon commented on test/ParsedownCheckboxTest.php
> +<li class="parsedown-task-list parsedown-task-list-open"><input type="checkbox" disabled /> test 4 &amp;lt;a&amp;gt;&amp;lt;/a&amp;gt;</li>
Please, don't modify the line. This change produce invalid HTML (double encoding)
With my proposal in ParsedownCheckbox.php, this test will pass

2019-05-30 09:06 UTC, doekenorg commented on ParsedownCheckbox.php
> +        return '<input type="checkbox" disabled /> ' . $this->line($text);
I changed up the implementation a bit to prevent setting the escaping if it wasn't set before just to be save. And this could all just live in a single `format` function.

2019-05-30 09:07 UTC, doekenorg commented on ParsedownCheckbox.php
> +        return '<input type="checkbox" checked disabled /> ' . $this->line($text);
I can't believe I missed that. I'm pretty new to testing, but this was just bonkers.

2019-05-30 09:08 UTC, doekenorg commented on ParsedownCheckbox.php
> +    const VERSION = '0.1.1';
Sure thing. Changed it to `0.2.0`.

2019-05-30 09:09 UTC, doekenorg commented on test/ParsedownCheckboxTest.php
> +<li class="parsedown-task-list parsedown-task-list-open"><input type="checkbox" disabled /> test 4 &amp;lt;a&amp;gt;&amp;lt;/a&amp;gt;</li>
Reset this. New code fixes all tests. I've included `phpunit/phpunit:^7.5` in the `require-dev` packages. Hope that's ok. Makes testing just a bit easier.

2019-05-30 10:45 UTC, leblanc-simon commented on ParsedownCheckbox.php
> +        return '<input type="checkbox" checked disabled /> ' . $this->line($text);
Good ! It's more elegant than mine :)

2019-05-30 10:46 UTC, leblanc-simon commented on ParsedownCheckbox.php
> +    const VERSION = '0.1.1';
Thanks !

2019-05-30 10:47 UTC, merged

2019-05-30 10:48 UTC, leblanc-simon commented
Thanks you for this PR !